// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;
    

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDaHeR7SVZo0Z1SVN91WG20c26jAbtYpYA',
    appId: '1:190076256918:web:c415465add7608c947f8b7',
    messagingSenderId: '190076256918',
    projectId: 'alu-connect-app',
    authDomain: 'alu-connect-app.firebaseapp.com',
    storageBucket: 'alu-connect-app.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAUrAn-sSsbyRSoPN2wWBprmSoutVdP7y4',
    appId: '1:190076256918:android:e5e1983dd1da818a47f8b7',
    messagingSenderId: '190076256918',
    projectId: 'alu-connect-app',
    storageBucket: 'alu-connect-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBgFLn18T0K-PjkX-fdbO-NG0LkckBW7bA',
    appId: '1:190076256918:ios:9b5ac54c71adee5b47f8b7',
    messagingSenderId: '190076256918',
    projectId: 'alu-connect-app',
    storageBucket: 'alu-connect-app.firebasestorage.app',
    iosBundleId: 'com.example.aluConnect',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBgFLn18T0K-PjkX-fdbO-NG0LkckBW7bA',
    appId: '1:190076256918:ios:9b5ac54c71adee5b47f8b7',
    messagingSenderId: '190076256918',
    projectId: 'alu-connect-app',
    storageBucket: 'alu-connect-app.firebasestorage.app',
    iosBundleId: 'com.example.aluConnect',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDaHeR7SVZo0Z1SVN91WG20c26jAbtYpYA',
    appId: '1:190076256918:web:aaec27c6f135231347f8b7',
    messagingSenderId: '190076256918',
    projectId: 'alu-connect-app',
    authDomain: 'alu-connect-app.firebaseapp.com',
    storageBucket: 'alu-connect-app.firebasestorage.app',
  );
}
